In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import json
import os
from datetime import datetime
import glob
import sys
from apikey import apikey

ModuleNotFoundError: No module named 'apikey'

In [11]:
api_key = str(apikey.apikey())
#lat='24.34'
#lon='10.99'

lat=[33.25,66.32,64.76,0.62,-32.09,0.50,47.77,-37.85,30.38,6.45]
lon=[-70.71,-70.95,27.52,-9.38,47.90,-48.31,-75.59,-64.08,30.37,-61.73]
resp_clima= pd.DataFrame()
today=datetime.now().date()
files_list = []

NameError: name 'apikey' is not defined

In [159]:
for lati, long in zip(lat,lon):
    url_weather = requests.get('https://api.openweathermap.org/data/2.5/weather?lat='+str(lati)+'&lon='+str(long)+'&appid='+api_key+'&units=metric&lang=sp&temp=celcius')
    clima_json= url_weather.json()
    df_weather_status = pd.json_normalize(clima_json)
    df_weather = pd.json_normalize(clima_json,"weather")
    df_weather_status[['main','description']] = df_weather[['main','description']]
    df_weather_status[['date']]=today
    df_total = pd.DataFrame(df_weather_status)
    df_resume =df_total.drop(columns='weather')
    resp_clima = df_resume.append(resp_clima)
resp_clima

,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,...,wind.gust,clouds.all,sys.country,sys.sunrise,sys.sunset,main,description,date,snow.1h,rain.1h
0,stations,10000,1676833853,-14400,3808236,Kilometro Treinta y Tres,200,-61.73,6.45,27.11,...,3.20,100,VE,1676802163,1676845149,Clouds,nubes,2023-02-19,NaN,NaN
0,stations,10000,1676833853,7200,353223,Madīnat as Sādāt,200,30.37,30.38,12.67,...,9.53,0,EG,1676781348,1676821759,Clear,cielo claro,2023-02-19,NaN,NaN
0,stations,10000,1676833853,-10800,3864283,Bernasconi,200,-64.08,-37.85,33.65,...,9.39,9,AR,1676800211,1676848229,Clear,cielo claro,2023-02-19,NaN,NaN
0,stations,957,1676833852,-18000,6076235,Monet,200,-75.59,47.77,-1.50,...,15.20,100,CA,1676808128,1676845837,Snow,nevada ligera,2023-02-19,0.15,NaN
0,stations,10000,1676833852,-10800,3387204,Soure,200,-48.31,0.50,24.97,...,7.18,100,BR,1676798656,1676842215,Rain,lluvia ligera,2023-02-19,NaN,0.87
0,stations,10000,1676833852,10800,0,,200,47.90,-32.09,22.46,...,3.92,25,NaN,1676773756,1676820937,Clouds,nubes dispersas,2023-02-19,NaN,NaN
0,stations,10000,1676833852,-3600,0,,200,-9.38,0.62,27.62,...,4.40,15,NaN,1676789319,1676832866,Clouds,algo de nubes,2023-02-19,NaN,NaN
0,stations,941,1676833851,7200,640660,Puolanka,200,27.52,64.76,-7.88,...,6.83,100,FI,1676786199,1676818276,Clouds,nubes,2023-02-19,NaN,NaN
0,stations,6958,1676833851,-18000,0,,200,-70.95,66.32,-37.67,...,4.31,89,NaN,1676810221,1676841517,Clouds,nubes,2023-02-19,NaN,NaN
0,stations,10000,1676833800,-18000,0,,200,-70.71,33.25,17.17,...,5.45,100,NaN,1676805775,1676845847,Clouds,nubes,2023-02-19,NaN,NaN

In [160]:
to_csv = resp_clima.to_csv('Historico/Clima_'+str(today)+'.csv',sep=',')

In [179]:
all_files = glob.glob('Historico/clima*.csv')
len(all_files)

1

In [175]:
for i in all_files:
    file = pd.read_csv(i)
    files_list.append(file)

df_total = pd.concat(files_list, ignore_index=True)
df_total

,Unnamed: 0,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,...,wind.gust,clouds.all,sys.country,sys.sunrise,sys.sunset,main,description,date,snow.1h,rain.1h
0,0,stations,10000,1676833853,-14400,3808236,Kilometro Treinta y Tres,200,-61.73,6.45,...,3.20,100,VE,1676802163,1676845149,Clouds,nubes,2023-02-19,NaN,NaN
1,0,stations,10000,1676833853,7200,353223,Madīnat as Sādāt,200,30.37,30.38,...,9.53,0,EG,1676781348,1676821759,Clear,cielo claro,2023-02-19,NaN,NaN
2,0,stations,10000,1676833853,-10800,3864283,Bernasconi,200,-64.08,-37.85,...,9.39,9,AR,1676800211,1676848229,Clear,cielo claro,2023-02-19,NaN,NaN
3,0,stations,957,1676833852,-18000,6076235,Monet,200,-75.59,47.77,...,15.20,100,CA,1676808128,1676845837,Snow,nevada ligera,2023-02-19,0.15,NaN
4,0,stations,10000,1676833852,-10800,3387204,Soure,200,-48.31,0.50,...,7.18,100,BR,1676798656,1676842215,Rain,lluvia ligera,2023-02-19,NaN,0.87
5,0,stations,10000,1676833852,10800,0,NaN,200,47.90,-32.09,...,3.92,25,NaN,1676773756,1676820937,Clouds,nubes dispersas,2023-02-19,NaN,NaN
6,0,stations,10000,1676833852,-3600,0,NaN,200,-9.38,0.62,...,4.40,15,NaN,1676789319,1676832866,Clouds,algo de nubes,2023-02-19,NaN,NaN
7,0,stations,941,1676833851,7200,640660,Puolanka,200,27.52,64.76,...,6.83,100,FI,1676786199,1676818276,Clouds,nubes,2023-02-19,NaN,NaN
8,0,stations,6958,1676833851,-18000,0,NaN,200,-70.95,66.32,...,4.31,89,NaN,1676810221,1676841517,Clouds,nubes,2023-02-19,NaN,NaN
9,0,stations,10000,1676833800,-18000,0,NaN,200,-70.71,33.25,...,5.45,100,NaN,1676805775,1676845847,Clouds,nubes,2023-02-19,NaN,NaN
10,0,stations,10000,1676833853,-14400,3808236,Kilometro Treinta y Tres,200,-61.73,6.45,...,3.20,100,VE,1676802163,1676845149,Clouds,nubes,2023-02-19,NaN,NaN
11,0,stations,10000,1676833853,7200,353223,Madīnat as Sādāt,200,30.37,30.38,...,9.53,0,EG,1676781348,1676821759,Clear,cielo claro,2023-02-19,NaN,NaN
12,0,stations,10000,1676833853,-10800,3864283,Bernasconi,200,-64.08,-37.85,...,9.39,9,AR,1676800211,1676848229,Clear,cielo claro,2023-02-19,NaN,NaN
13,0,stations,957,1676833852,-18000,6076235,Monet,200,-75.59,47.77,...,15.20,100,CA,1676808128,1676845837,Snow,nevada ligera,2023-02-19,0.15,NaN
14,0,stations,10000,1676833852,-10800,3387204,Soure,200,-48.31,0.50,...,7.18,100,BR,1676798656,1676842215,Rain,lluvia ligera,2023-02-19,NaN,0.87
15,0,stations,10000,1676833852,10800,0,NaN,200,47.90,-32.09,...,3.92,25,NaN,1676773756,1676820937,Clouds,nubes dispersas,2023-02-19,NaN,NaN
16,0,stations,10000,1676833852,-3600,0,NaN,200,-9.38,0.62,...,4.40,15,NaN,1676789319,1676832866,Clouds,algo de nubes,2023-02-19,NaN,NaN
17,0,stations,941,1676833851,7200,640660,Puolanka,200,27.52,64.76,...,6.83,100,FI,1676786199,1676818276,Clouds,nubes,2023-02-19,NaN,NaN
18,0,stations,6958,1676833851,-18000,0,NaN,200,-70.95,66.32,...,4.31,89,NaN,1676810221,1676841517,Clouds,nubes,2023-02-19,NaN,NaN
19,0,stations,10000,1676833800,-18000,0,NaN,200,-70.71,33.25,...,5.45,100,NaN,1676805775,1676845847,Clouds,nubes,2023-02-19,NaN,NaN
20,0,stations,10000,1676833853,-14400,3808236,Kilometro Treinta y Tres,200,-61.73,6.45,...,3.20,100,VE,1676802163,1676845149,Clouds,nubes,2023-02-19,NaN,NaN
21,0,stations,10000,1676833853,7200,353223,Madīnat as Sādāt,200,30.37,30.38,...,9.53,0,EG,1676781348,1676821759,Clear,cielo claro,2023-02-19,NaN,NaN
22,0,stations,10000,1676833853,-10800,3864283,Bernasconi,200,-64.08,-37.85,...,9.39,9,AR,1676800211,1676848229,Clear,cielo claro,2023-02-19,NaN,NaN
23,0,stations,957,1676833852,-18000,6076235,Monet,200,-75.59,47.77,...,15.20,100,CA,1676808128,1676845837,Snow,nevada ligera,2023-02-19,0.15,NaN
24,0,stations,10000,1676833852,-10800,3387204,Soure,200,-48.31,0.50,...,7.18,100,BR,1676798656,1676842215,Rain,lluvia ligera,2023-02-19,NaN,0.87
25,0,stations,10000,1676833852,10800,0,NaN,200,47.90,-32.09,...,3.92,25,NaN,1676773756,1676820937,Clouds,nubes dispersas,2023-02-19,NaN,NaN
26,0,stations,10000,1676833852,-3600,0,NaN,200,-9.38,0.62,...,4.40,15,NaN,1676789319,1676832866,Clouds,algo de nubes,2023-02-19,NaN,NaN
27,0,stations,941,1676833851,7200,640660,Puolanka,200,27.52,64.76,...,6.83,100,FI,1676786199,1676818276,Clouds,nubes,2023-02-19,NaN,NaN
28,0,stations,6958,1676833851,-18000,0,NaN,200,-70.95,66.32,...,4.31,89,NaN,1676810221,1676841517,Clouds,nubes,2023-02-19,NaN,NaN
29,0,stations,10000,1676833800,-18000,0,NaN,200,-70.71,33.25,...,5.45,100,NaN,1676805775,1676845847,Clouds,nubes,2023-02-19,NaN,NaN
30,0,stations,10000,1676833853,-14400,3808236,Kilometro Treinta y Tres,200,-61.73,6.45,...,3.20,100,VE,1676802163,1676845149,Clouds,nubes,2023-02-19,NaN,NaN
31,0,stations,10000,1676833853,7200,353223,Madīnat as Sādāt,200,30.37,30.38,...,9.53,0,EG,1676781348,1676821759,Clear,cielo claro,2023-02-19,NaN,NaN
32,0,stations,10000,1676833853,-10800,3864283,Bernasconi,200,-64.08,-37.85,...,9.39,9,AR,1676800211,1676848229,Clear,cielo claro,2023-02-19,NaN,NaN
33,0,stations,957,1676833852,-18000,6076235,Monet,200,-75.59,47.77,...,15.20,100,CA,1676808128,1676845837,Snow,nevada ligera,2023-02-19,0.15,NaN
34,0,stations,10000,1676833852,-10800,3387204,Soure,200,-48.31,0.50,...,7.18,100,BR,1676798656,1676842215,Rain,lluvia ligera,2023-02-19,NaN,0.87
35,0,stations,10000,1676833852,10800,0,NaN,200,47.90,-32.09,...,3.92,25,NaN,1676773756,1676820937,Clouds,nubes dispersas,2023-02-19,NaN,NaN
36,0,stations,10000,1676833852,-3600,0,NaN,200,-9.38,0.62,...,4.40,15,NaN,1676789319,1676832866,Clouds,algo de nubes,2023-02-19,NaN,NaN
37,0,stations,941,1676833851,7200,640660,Puolanka,200,27.52,64.76,...,6.83,100,FI,1676786199,1676818276,Clouds,nubes,2023-02-19,NaN,NaN
38,0,stations,6958,1676833851,-18000,0,NaN,200,-70.95,66.32,...,4.31,89,NaN,1676810221,1676841517,Clouds,nubes,2023-02-19,NaN,NaN
39,0,stations,10000,1676833800,-18000,0,NaN,200,-70.71,33.25,...,5.45,100,NaN,1676805775,1676845847,Clouds,nubes,2023-02-19,NaN,NaN

In [196]:
directorio = 'Total'
path = 'C:/Users/aleja/Documents/Python Scripts'

full = os.path.join(path,directorio)

if os.path.exists(full):
    print('existe')
else:
    os.mkdir(full)
to_csv = resp_clima.to_csv('Total/TotalFechas.csv',sep=',')